### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by shenoysuraj** [Kidplayer666/Tiny-random-game#2] opened 2020-07-06 22:37 UTC
Please use pip to create a file called requirements.txt, which makes it easier for us to setup the game.

**Comment by Kidplayer666** [comment] 2020-07-07 08:14
I don't know how to do it. I put in the README file the external libraries used (use "pip install guizero" , it's the only external library)

> 
> 
> Please use pip to create a file called requirements.txt, which makes it easier for us to setup the game.

Duplicate of #

**Comment by shenoysuraj** [comment] 2020-07-07 08:19
Thank you. I am already making apps with guizero, so I already have it installed.

But in the future, when you have bigger projects, you should create a requirements.txt from pip.

**Comment by Kidplayer666** [comment] 2020-07-07 08:30
> 
> 
> Thank you. I am already making apps with guizero, so I already have it installed.
> 
> But in the future, when you have bigger projects, you should create a requirements.txt from pip.

Thank you, just done it. Any more feedback?

**Comment by shenoysuraj** [comment] 2020-07-07 08:50
Nothing else really, I am still in the learning process, so that's all I have.

**Comment by Kidplayer666** [comment] 2020-07-07 08:52
Duplicate of #

> 
> 
> Nothing else really, I am still in the learning process, so that's all I have.

I'm still learning too, it was more in the sense of what features should I add next

**Closed as completed** 2020-07-07 08:57 UTC
